# VNPay Sandbox
vnpay.version=2.1.0
vnpay.command=pay
vnpay.tmn-code=1N3OPOMK
vnpay.hash-secret=7N2CMCKL126LQ2MVJ2034ERINFMI1DHT
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# N?u web ch?y tr?c ti?p ? localhost:8080
vnpay.return-url=http://localhost:8080/vnpay-return
vnpay.ipn-url=http://localhost:8080/vnpay-ipn